### PR TITLE
test: Add test case for RunsOldestTaskPolicy #1335

### LINKED ISSUE #1335: Add test case for RunsOldestTaskPolicy
Code classes that need to develop unit tests:

- `cn.hippo4j.common.executor.support.RunsOldestTaskPolicy`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

### PR DESCRIPTION
**Pull request by annippolito**
Fixes #1335

Changes proposed in this pull request:
- Add test case for RunsOldestTaskPolicy #1335

> Check mailbox configuration when submitting. [Contributor Guide](https://hippo4j.cn/community/contributor-guide)

### CODE REVIEW

**Comment by magestacks** [comment]
Please check why unit test coverage is not changing.

image

image

**Comment by annippolito** [comment]
So now it looks, good :-)
Screenshot 2023-05-26 at 11 34 29

What I found is interesting, I were using ``org.junit.jupiter.api`` and the class were not considered by codecov, I found this issue in other classes, looks for example at : ``BlockingQueueTypeEnumTest``
It seems well tested but his coverage is zero, for the same reason:

Screenshot 2023-05-26 at 11 38 28

**Comment by magestacks** [comment]
you are right. I will re-run the CI process

**Comment by annippolito** [comment]
thanks, do you think may I fix that test class also? to increase a bit the coverage

**Comment by magestacks** [comment]
> thanks, do you think may I fix that test class also? to increase a bit the coverage

@annippolito of course

**Review by magestacks — APPROVED** [review]

**Comment by annippolito** [comment]
@magestacks it looks good, in the next pr the coverage is increased more than 4% :-) https://github.com/opengoofy/hippo4j/pull/1349

**Pull request merged**
