### PR TITLE
feature: hippo4j config model in zookeeper config before check

### LINKED ISSUE #1439: [Enhancement] Check the required fields such as the configuration center when the Config mode starts
### Search before asking

- [X] I had searched in the [issues](https://github.com/opengoofy/hippo4j/issues) and found no similar issues.

### Enhancement Request

Check the required fields such as the configuration center when the Config mode starts.

- [x] Nacos @2084276225  https://github.com/opengoofy/hippo4j/pull/1438
- [x] Zookeeper @xjlgod https://github.com/opengoofy/hippo4j/pull/1457
- [x] Apollo @Myboolean https://github.com/opengoofy/hippo4j/pull/1452
- [x] ETCD @liguangling-lgl https://github.com/opengoofy/hippo4j/pull/1440
- [x] Polaris @mazengrun  https://github.com/opengoofy/hippo4j/pull/1470
- [ ] Consul

### Describe the solution you'd like

`BeforeCheckConfiguration` for validation.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

### PR DESCRIPTION
**Pull request by xjlgod**
Fixes #1439

### CODE REVIEW

**Comment by xjlgod** [comment]
By the way, I think using  propertiesClassName to choose check logic in "cn/hippo4j/core/enable/BeforeCheckConfiguration.java"  is not a good way. For instance, if the propertiesClassName is set to “SpringBootstrapConfigProperties”  will do nothing.

**Review by magestacks — APPROVED** [review]

**Comment by magestacks** [comment]
@xjlgod Please resolve code conflicts.

**Comment by xjlgod** [comment]
> @xjlgod Please resolve code conflicts.

I have done it. How about the question I talked.

**Review by magestacks — APPROVED** [review]

**Comment by magestacks** [comment]
> By the way, I think using propertiesClassName to choose check logic in "cn/hippo4j/core/enable/BeforeCheckConfiguration.java" is not a good way. For instance, if the propertiesClassName is set to “SpringBootstrapConfigProperties” will do nothing.

If there are any problems with the current design, I will deal with them collectively.

**Pull request merged**
