### PR TITLE
Add test case for Joiner

### LINKED ISSUE #1328: [Unit Test] Add test case for Joiner
Code classes that need to develop unit tests:

- `cn.hippo4j.common.toolkit.Joiner`

Please refer to the manual for the first contribution: [guide](https://hippo4j.cn/community/contributor-guide)

Unit test development refers to the following two examples:

- `cn.hippo4j.core.executor.DynamicThreadPoolExecutorTest`
- `cn.hippo4j.core.executor.ExtensibleThreadPoolExecutorTest`

### PR DESCRIPTION
**Pull request by barret-yzh**
Fixes #1328 

Add test case for Joiner

### CODE REVIEW

**Comment by magestacks** [comment]
Check unit test coverage

**Comment by barret-yzh** [comment]
Every time I synchronize my repository before I pull the request,Idont' know why it happens

**Comment by barret-yzh** [comment]
> Check unit test coverage
Every time I synchronize my repository before I pull the request,Idont' know why it happens

**Comment by magestacks** [comment]
You can refer to historical PR requests to check why the coverage is low

**Pull request closed without merging**
